# Generated by Django 4.1.4 on 2022-12-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cpf',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
